### ISSUE TITLE
An error when typing make zeep-test to install libzeep 3.0.5

### ISSUE THREAD

**Issue by YuhaoTan2** [mhekkel/libzeep#10]
When I type `make zeep-test` to install libzeep 3.0.5, I get an error.
I have changed BOOST to /gpfs/user/tanyh/miniconda3/envs/ppi, and changed PREFIX to /gpfs/user/tanyh/miniconda3/envs/ppi. Then I type `make zeep-test` and it sends `make: *** [zeep-test] Error 1`. I am not sure whether I am using the right way to install, and I have not found a detailed explanation about installation. So how can I install libzeep? The error in detail is as below.

makefile:126: obj/doctype.d: No such file or directory
makefile:126: obj/document.d: No such file or directory
makefile:126: obj/exception.d: No such file or directory
makefile:126: obj/node.d: No such file or directory
makefile:126: obj/soap-envelope.d: No such file or directory
makefile:126: obj/parser.d: No such file or directory
makefile:126: obj/reply.d: No such file or directory
makefile:126: obj/request.d: No such file or directory
makefile:126: obj/md5.d: No such file or directory
makefile:126: obj/message_parser.d: No such file or directory
makefile:126: obj/connection.d: No such file or directory
makefile:126: obj/http-server.d: No such file or directory
makefile:126: obj/preforked-http-server.d: No such file or directory
makefile:126: obj/soap-server.d: No such file or directory
makefile:126: obj/unicode_support.d: No such file or directory
makefile:126: obj/webapp.d: No such file or directory
makefile:126: obj/webapp-el.d: No such file or directory
makefile:126: obj/xpath.d: No such file or directory
makefile:126: obj/writer.d: No such file or directory
make: Warning: File `makefile' has modification time 46 s in the future
mkdir -p obj
g++ -MD -c -o obj/zeep-test.o zeep-test.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/doctype.o src/doctype.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/document.o src/document.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/exception.o src/exception.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/node.o src/node.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/soap-envelope.o src/soap-envelope.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/parser.o src/parser.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/reply.o src/reply.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/request.o src/request.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/md5.o src/md5.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/message_parser.o src/message_parser.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/connection.o src/connection.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/http-server.o src/http-server.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/preforked-http-server.o src/preforked-http-server.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/soap-server.o src/soap-server.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/unicode_support.o src/unicode_support.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/webapp.o src/webapp.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/webapp-el.o src/webapp-el.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/xpath.o src/xpath.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
g++ -MD -c -o obj/writer.o src/writer.cpp -O2 -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -I. -fPIC -pthread -std=c++11  -Wall -g
ar rc libzeep.a obj/doctype.o obj/document.o obj/exception.o obj/node.o obj/soap-envelope.o obj/parser.o obj/reply.o obj/request.o obj/md5.o obj/message_parser.o obj/connection.o obj/http-server.o obj/preforked-http-server.o obj/soap-server.o obj/unicode_support.o obj/webapp.o obj/webapp-el.o obj/xpath.o obj/writer.o
ranlib libzeep.a
g++ -I/gpfs/user/tanyh/miniconda3/envs/ppi/include -o zeep-test -I. obj/zeep-test.o libzeep.a -L/gpfs/user/tanyh/miniconda3/envs/ppi/lib -lboost_system -lboost_thread -lboost_filesystem -lboost_regex -lboost_math_c99 -lboost_random -lstdc++ -lm -lpthread -lrt -g -lboost_date_time -lboost_regex
/usr/bin/ld: warning: libicudata.so.67, needed by /gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicui18n.so.67, needed by /gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.67, needed by /gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so, not found (try using -rpath or -rpath-link)
obj/zeep-test.o: In function `boost::re_detail_107200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
/gpfs/user/tanyh/miniconda3/envs/ppi/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
obj/zeep-test.o: In function `bool boost::regex_match<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)':
/gpfs/user/tanyh/miniconda3/envs/ppi/include/boost/regex/v4/perl_matcher.hpp:391: undefined reference to `boost::re_detail_107200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
obj/zeep-test.o: In function `boost::cpp_regex_traits<char>::transform_primary(char const*, char const*) const':
/gpfs/user/tanyh/miniconda3/envs/ppi/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_107200::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
obj/zeep-test.o: In function `boost::cpp_regex_traits<char>::transform(char const*, char const*) const':
/gpfs/user/tanyh/miniconda3/envs/ppi/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_107200::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
obj/zeep-test.o: In function `boost::re_detail_107200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_match()':
/gpfs/user/tanyh/miniconda3/envs/ppi/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1108: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
libzeep.a(request.o): In function `zeep::http::request::is_mobile() const':
/gpfs/user/tanyh/miniconda3/envs/ppi/include/boost/regex/v4/perl_matcher.hpp:391: undefined reference to `boost::re_detail_107200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
libzeep.a(request.o): In function `boost::re_detail_107200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::perl_matcher(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, __gnu_cxx::__normal_iterator<char const*, std::string>)':
/gpfs/user/tanyh/miniconda3/envs/ppi/include/boost/regex/v4/perl_matcher.hpp:391: undefined reference to `boost::re_detail_107200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
libzeep.a(request.o): In function `boost::re_detail_107200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
/gpfs/user/tanyh/miniconda3/envs/ppi/include/boost/regex/v4/perl_matcher_common.hpp:346: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `u_isspace_67'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `icu_67::Locale::~Locale()'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `u_digit_67'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `icu_67::Collator::createInstance(icu_67::Locale const&, UErrorCode&)'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `u_charFromName_67'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `icu_67::Locale::Locale()'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `u_isblank_67'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `u_charType_67'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `u_tolower_67'
/gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so: undefined reference to `icu_67::Locale::Locale(icu_67::Locale const&)'
collect2: error: ld returned 1 exit status
make: *** [zeep-test] Error 1

**Comment by mhekkel** [comment]
By looking at the error messages I think you might have multiple versions of boost on your disk. Or you have a couple of boost libraries copied over from another system, but they need yet another library. See e.g. "warning: libicudata.so.67, needed by /gpfs/user/tanyh/miniconda3/envs/ppi/lib/libboost_regex.so, not found" That means that the library libicudata.so.67 was used when building the libboost_regex.so file, but it cannot be found now.

**Comment by YuhaoTan2** [comment]
Thanks! Finally, I found the error was because I installed BOOST with conda. I compiled BOOST from source, add BOOST to LD_LIBRARY_PATH, and compiled libzeep successfully.
