### ISSUE TITLE
find Boost packages

### ISSUE THREAD

**Issue by zyzhang1992** [mhekkel/libzeep#12]
Greetings, 

I am trying to compile libzeep with our own installation of boost on the system. I needed to set the following, 
export Boost_INCLUDE_DIR=/share/software/user/open/boost/1.79.0/include

However, the CMakeList.txt seems to interpret the include location as libzeep/$Boost_INCLUDE_DIR, where libzeep is the libzeep git clone directory. 

Thanks for your attention to this issue!

**Comment by mhekkel** [comment]
If you need to specify a Boost installation directory, you should use the BOOST_ROOT variable like this:

```bash
cd libzeep/build
cmake .. -DBOOST_ROOT=/share/software/user/open/boost/1.79.0/
etc.
```

This is the preferred way of specifying boost, as documented in the FindBoost.cmake file.

**Comment by zyzhang1992** [comment]
Thank you. That worked.


________________________________
