### ISSUE TITLE
make only builds the static library

### ISSUE THREAD

**Issue by jonblack** [mhekkel/libzeep#5]
Running `make` builds `libzeep.a` (static library) but not `libzeep.so.3.0.3` (dynamic library). The dynamic library is only created when `make install` is run.

Likewise, if you run `make install` on a clean repository, it will fail because it can't find `libzeep.a`, meaning that `make install` doesn't trigger a static library build.

**Comment by mhekkel** [comment]
I've updated the code to include a autoconf configure script along with a new makefile capable of creating whatever was selected by configure.
