### ISSUE TITLE
make install should call ldconfig on linux systems

### ISSUE THREAD

**Issue by jonblack** [mhekkel/libzeep#7]
`make install` copies the libraries to `/usr/local/bin` but doesn't run `ldconfig`. On Linux systems this updates a cache (`/etc/ld.so.cache`) used by programs to more efficiently use libraries. If the cache isn't updated, an error like the following will appear:

```
root@75c8bd800631:/deps/xssp/xssp-2.2.7# mkhssp
mkhssp: error while loading shared libraries: libzeep.so.3.0: cannot open shared object file: No such file or directory
```

[This page](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html) on shared libraries states that:

> running ldconfig is often one of the steps performed by package managers when installing a library.

I have no idea what the windows equivalent would be.

**Comment by mhekkel** [comment]
You expect a full makefile with all the required parts in place. And you are right, it should have been that way. Unfortunately for you, my goal was to have something quick and dirty to create only the static library since that's what I use myself.

But you're right, I should fix this.

**Comment by mhekkel** [comment]
fixed
