### ISSUE TITLE
old tags seem to have changed

### ISSUE THREAD

**Issue by cbaakman** [mhekkel/libzeep#9]
Our software https://github.com/cmbi/mrs depends on libzeep v3.0.3. Now however, when we try to rebuild, it seems as if things have moved in this old tag. For example:

src/M6Server.h:17:31: fatal error: zeep/el/element.hpp: No such file or directory

Is there a way to access the old setup?

**Comment by mhekkel** [comment]
Version 3..0.3 did not have a zeep/el/element.hpp file.

Perhaps you're trying to build MRS using the master from libzeep at github? This new version has changed considerably. You should still be able to check out version 3.0.3 using its tag.

To do so, try:

$ git checkout v3.0.3

regards, -maarten
